### ISSUE TITLE
New feature request - Turn On/Off, see history...etc.

### ISSUE THREAD

**Issue by ethrashakarchi** [yesadahmed/xrmtoolboxdocumentation#1]
Finally we can see new plugin/tool in the XrmToolbox that is related to Power Automate. With the increasing in using PA, the community needs such a great tool to help with common tasks that is surprisingly not easily available.

I'd like to request considering extending the tool or create an alternate version of the tool that provides a high level status view of current Power Automates for a Power Apps/CE instance. It can be filtered by solution or just all. The user can see which one is On/Off and turn them ON/OFF from within the tool.

An even more important feature would be to display a running history sorted by time. Currently we can open each Power Automate in the make.powerapps.com portal and see its history. It is very hard to see all history in one page from all power automates. Will be great if we can also filter history by error so I can use this XrmToolbox to monitor the failed jobs. In the past, we used to be able to go to System Jobs in CRM and see failed workflows. We need a similar functionality for Power Automates basically. This will be the first tool of its kind to do that.

**Comment by yesadahmed** [comment]
Hi ethrashakarchi 

Please have a look into my new xrmtoolbox's plugin 
https://github.com/yesadahmed/PowerAutomateManagerDocs/blob/main/README.md

https://www.xrmtoolbox.com/plugins/PowerAutomateCloudManger/
it has helping video as well to get started.
https://www.youtube.com/watch?v=Y1SMLUVG-hQ

**Comment by ethrashakarchi** [comment]
Thanks @yesadahmed, I had a look at the video and this is amazing work. Well done mate. I look forward to using the new xrmtoolbox plugin, after I register the Azure app of course :)

Thanks for your commitment and contribution to the Power Platform community.
